name: Run Tests

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT : development
      SECRET_KEY : secret_key
      RENDER_EXTERNAL_HOSTNAME: localhost
      GOOGLE_CLIENT_ID: 1
      GOOGLE_SECRET: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.3

      - run: python -m pip install --upgrade pip
      - run: pip install -r req.txt
      - run: python manage.py test